import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from sqlalchemy.orm import Session
from app.models.models import Mine, ComplianceObligation, CAPA, Observation

def generate_mine_compliance_pdf(db: Session, mine_id: str) -> bytes:
    mine = db.query(Mine).filter(Mine.id == mine_id).first()
    if not mine:
        raise ValueError("Mine not found")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
    story = []

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E293B')
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748B')
    )
    h2_style = ParagraphStyle(
        'SectionH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=12,
        spaceAfter=6
    )
    body_style = styles['Normal']

    # Header
    story.append(Paragraph("MINISTRY OF COAL — STATUTORY COMPLIANCE REPORT", title_style))
    story.append(Paragraph(f"<b>Mine Name:</b> {mine.name} ({mine.code}) | <b>Subsidiary:</b> {mine.subsidiary.name} | <b>Type:</b> {mine.mine_type} | <b>Generated:</b> {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0EA5E9'), spaceAfter=15))

    # Summary Statistics
    total_obligations = db.query(ComplianceObligation).filter(ComplianceObligation.mine_id == mine_id).count()
    compliant_obligations = db.query(ComplianceObligation).filter(ComplianceObligation.mine_id == mine_id, ComplianceObligation.status == "COMPLIANT").count()
    total_capas = db.query(CAPA).filter(CAPA.mine_id == mine_id).count()
    open_capas = db.query(CAPA).filter(CAPA.mine_id == mine_id, CAPA.status.in_(["OPEN", "IN_PROGRESS"])).count()
    escalated_capas = db.query(CAPA).filter(CAPA.mine_id == mine_id, CAPA.status == "ESCALATED").count()

    comp_rate = round((compliant_obligations / max(1, total_obligations)) * 100.0, 1)

    summary_data = [
        ["Statutory Obligations", f"{compliant_obligations} / {total_obligations} Compliant ({comp_rate}%)"],
        ["Total CAPAs Logged", f"{total_capas}"],
        ["Open / Pending CAPAs", f"{open_capas}"],
        ["Escalated SLA Breaches", f"{escalated_capas}"],
        ["Mine Risk Index Level", f"{'HIGH' if open_capas > 3 else 'MODERATE / STABLE'}"]
    ]

    t_summary = Table(summary_data, colWidths=[200, 320])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#334155')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 15))

    # Active CAPAs Table
    story.append(Paragraph("Active Corrective & Preventive Actions (CAPA)", h2_style))
    capas = db.query(CAPA).filter(CAPA.mine_id == mine_id).order_by(CAPA.created_at.desc()).limit(10).all()

    capa_table_data = [["Title / Category", "Severity", "Assigned To", "Status", "SLA Due Date"]]
    for c in capas:
        capa_table_data.append([
            Paragraph(c.title[:45], body_style),
            c.severity,
            c.assigned_to_name or "Unassigned",
            c.status,
            c.sla_due_date.strftime('%Y-%m-%d')
        ])

    t_capa = Table(capa_table_data, colWidths=[180, 60, 110, 80, 90])
    t_capa.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0,0), (-1,-1), 5),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F1F5F9')])
    ]))
    story.append(t_capa)
    story.append(Spacer(1, 20))

    # Audit Footnote
    story.append(Paragraph("<i>This statutory compliance report is auto-generated by CoalGov AI Platform. All records are cryptographically sealed with SHA-256 hash chaining.</i>", subtitle_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
